chore(scripts): change shebangs to bash (#19)
* chore: create aliases to simplify script usage

* chore(docs): update setup instructions

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -1,6 +1,7 @@
-#!/bin/sh -ex
+#!/bin/bash -e
+#
+# Install node dependencies and githooks.
 
-command -v pre-commit &> /dev/null && pre-commit install --hook-type commit-msg || echo >&2 "pre-commit not found."
+command -v pre-commit &> /dev/null && pre-commit install --hook-type commit-msg || echo >&2 'pre-commit not found.'
 
 npm ci
-# npm link
